[RF] - add table profile(user not available)
ZagirNur/gotestbot pull request #1
Opened 2022-02-11 13:26 UTC by mazanur

- add logic for lazy init user

2022-02-11 17:39 UTC, ZagirNur requested changes

2022-02-11 17:39 UTC, ZagirNur commented on internal/bot/bot_handler/bot.go
> +	u.GetUser()
Не вижу смысла тут выполнять этот код, лучше в самом sdk это делать

2022-02-11 17:39 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +type UserProvider interface {
Я ранее объединил все интерфейсы нужные для sdk, думаю не нужно порождать интерфейс еще один, просто добавить метод

2022-02-11 17:39 UTC, ZagirNur commented on sdk/tgbot/update.go
> +func (u *Update) GetUser() *User {
Давай тут структуру передавать, не вижу смысла передавать указатель

2022-02-11 17:39 UTC, ZagirNur commented on sdk/tgbot/update.go
> +		tgUser, err := getFrom(&u.Update)
тут тоже лучше возвращать структуру, иначе ниже будет npe при ошибке

2022-02-13 10:07 UTC, ZagirNur commented on cmd/app/config.go
> +	TgToken string `env:"TG_TOKEN,notEmpty"  envExpand:"true" envDefault:"1295847044:AAFKKNW77aNNVRlcEBXsmO10tr3odcUei-0"`
убери токен)

2022-02-13 10:09 UTC, mazanur commented on cmd/app/config.go
> +	TgToken string `env:"TG_TOKEN,notEmpty"  envExpand:"true" envDefault:"1295847044:AAFKKNW77aNNVRlcEBXsmO10tr3odcUei-0"`
там его нет, старые изменение смотришь

2022-02-13 10:13 UTC, ZagirNur commented on internal/dao/pg_rep.go
> +func (r *Repository) SaveUser(user tgbot.User) error {
мне кажется апдейты при каждом запросы делать не очень хорошо, давай отдельный селект, а потом такой апдейт

2022-02-13 10:14 UTC, ZagirNur commented on sdk/tgbot/model.go
> +}
добавь в конец перенос строки

2022-02-13 10:16 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +		log.Err(err).Msg("")
логирование можно убрать, выше логгируется

2022-02-13 10:18 UTC, mazanur commented on sdk/tgbot/model.go
> +}
для чего?

2022-02-13 10:23 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +		log.Error().Err(err).Msgf("cannot save user %s", user)
тоже можно логирование убрать, вместо этого обернуть

2022-02-13 10:24 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +	user, err := b.SaveUser(update)
логика дублируется, метод выше то же самое делает

2022-02-13 10:37 UTC, mazanur commented on sdk/tgbot/tgbot.go
> +	user, err := b.SaveUser(update)
потому что у тебя 2 WrapUpdate в 2 разных местах вызывется

2022-02-13 10:38 UTC, ZagirNur commented on cmd/app/config.go
> +	TgToken string `env:"TG_TOKEN,notEmpty"  envExpand:"true" envDefault:"1295847044:AAFKKNW77aNNVRlcEBXsmO10tr3odcUei-0"`
я видимо успел до твоего коммита открыть)

2022-02-13 10:38 UTC, mazanur commented on sdk/tgbot/tgbot.go
> +	user, err := b.SaveUser(update)
потому что у тебя нескольких местах WrapUpdate вызывается, не хотелось это делать в методе WrapUpdate

2022-02-13 10:39 UTC, ZagirNur commented on sdk/tgbot/model.go
> +}
ну хз, гитхаб акцентирует на этом внимение)

2022-02-13 10:46 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +func (u *Bot) SaveUser(update *tgbotapi.Update) (User, error) {
u *Bot -> b *Bot

2022-02-13 10:47 UTC, mazanur commented on sdk/tgbot/tgbot.go
> +func (u *Bot) SaveUser(update *tgbotapi.Update) (User, error) {
во ты задрал а

2022-02-13 10:49 UTC, merged

2022-02-13 10:49 UTC, ZagirNur commented on sdk/tgbot/tgbot.go
> +func (u *Bot) SaveUser(update *tgbotapi.Update) (User, error) {
ну че, мне голенд ругается😅